version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: account-postgres
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - summershop-network

  mongodb:
    image: mongo:6.0
    container_name: item-mongodb
    environment:
      MONGO_INITDB_DATABASE: item_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - summershop-network

volumes:
  postgres-data:
  mongo-data:

networks:
  summershop-network:
    driver: bridge