server:
  port: 8082

spring:
  application:
    name: item-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/item_db
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.summershop.item: DEBUG